import Link from "next/link";
import { updateH5SiteSettingAction } from "@/app/admin/actions";
import { AdminContentService } from "@/server/services/admin-content-service";

export default async function SiteSettingsPage({ searchParams }: { searchParams: Promise<{ saved?: string }> }) {
  const [{ config, status, updatedAt }, query] = await Promise.all([new AdminContentService().getH5SiteSetting(), searchParams]);
  return <main><div className="admin-page-heading"><div><p className="eyebrow">H5 页面结构</p><h1>全局页面设置</h1><p>维护固定入口、品牌引导页和档案首页；分类、卡片与报告资料在“分类与报告”中管理。</p></div><a className="button button-secondary" href="/" target="_blank" rel="noreferrer">打开前端 H5</a></div>{query.saved === "1" && <p className="save-message" role="status">全局页面设置已保存。</p>}
    <section className="admin-section h5-hierarchy"><h2>前后台功能层级</h2><ol><li><strong>固定入口 `/go`</strong><span>进入品牌引导页，无独立内容。</span></li><li><strong>品牌引导页 `/`</strong><span>品牌、标题、引导文案、按钮及自动进入时间。</span></li><li><strong>档案首页 `/reports`</strong><span>首页标题、证据过渡区、品牌初心及分类入口。</span></li><li><strong>分类详情</strong><span><Link href="/admin/modules">管理分类、卡片与排序</Link></span></li><li><strong>报告资料页</strong><span>在对应卡片下管理图片、PDF和外链。</span></li></ol></section>
    <form action={updateH5SiteSettingAction} className="admin-form site-settings-form"><section className="admin-section"><h2>品牌引导页</h2><label>品牌名称<input name="brandName" defaultValue={config.brandName} required maxLength={100}/></label><label>主标题<span>可换行输入。</span><textarea name="guideTitle" defaultValue={config.guideTitle} required/></label><label>操作提示<input name="guideDescription" defaultValue={config.guideDescription} required/></label><label>按钮文字<input name="guideButtonText" defaultValue={config.guideButtonText} required/></label><label>自动进入时间（秒）<input name="guideDelaySeconds" type="number" min="0" max="10" step="1" defaultValue={config.guideDelaySeconds} required/></label></section>
      <section className="admin-section"><h2>档案首页</h2><label>顶部小标题<input name="archiveEyebrow" defaultValue={config.archiveEyebrow} required/></label><label>页面主标题<input name="archiveTitle" defaultValue={config.archiveTitle} required/></label><label>页面说明<textarea name="archiveDescription" defaultValue={config.archiveDescription} required/></label><label>证据区主标题<input name="evidenceTitle" defaultValue={config.evidenceTitle} required/></label><label>证据区副标题<input name="evidenceSubtitle" defaultValue={config.evidenceSubtitle} required/></label></section>
      <section className="admin-section"><h2>品牌初心区</h2><label>顶部小标题<input name="storyEyebrow" defaultValue={config.storyEyebrow} required/></label><label>主标题<textarea name="storyTitle" defaultValue={config.storyTitle} required/></label><label>说明文案<textarea name="storyDescription" defaultValue={config.storyDescription} required/></label></section>
      <section className="admin-section"><h2>发布状态</h2><label>设置状态<select name="status" defaultValue={status}><option value="DRAFT">草稿（前端继续使用默认配置）</option><option value="PUBLISHED">发布并应用到 H5</option><option value="OFFLINE">下线（前端使用默认配置）</option></select></label>{updatedAt && <small>最后保存：{updatedAt.toLocaleString("zh-CN")}</small>}</section><button className="button button-primary">保存全局页面设置</button></form>
  </main>;
}
