import { notFound } from "next/navigation";
import Link from "next/link";
import { AdminContentService } from "@/server/services/admin-content-service";
import { createAssetAction, deleteAssetAction, deleteCardAction, updateAssetAction, updateCardAction } from "../../../actions";

const statusOptions = <><option value="DRAFT">草稿</option><option value="PUBLISHED">已发布</option><option value="OFFLINE">已下线</option></>;
export default async function CardPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const service = new AdminContentService(); const card = await service.getCard(id); if (!card) notFound(); const assets = await service.listAssets(id);
  return <main><p><Link href={`/admin/modules/${card.moduleId}`}>← 返回所属模块</Link></p><h1>{card.title}</h1><form action={updateCardAction} className="admin-form"><input type="hidden" name="id" value={id}/><input type="hidden" name="moduleId" value={card.moduleId}/><input name="title" defaultValue={card.title} required/><textarea name="description" defaultValue={card.description ?? ""}/><input name="buttonText" defaultValue={card.buttonText}/><input name="footerNote" defaultValue={card.footerNote ?? ""}/><input name="sortOrder" type="number" min="0" defaultValue={card.sortOrder}/><select name="status" defaultValue={card.contentStatus}>{statusOptions}</select><button>保存卡片</button></form><form action={deleteCardAction}><input type="hidden" name="id" value={id}/><input type="hidden" name="moduleId" value={card.moduleId}/><button className="danger">软删除卡片</button></form><h2>新建资料元数据</h2><form action={createAssetAction} className="admin-form"><input type="hidden" name="reportCardId" value={id}/><input name="title" placeholder="标题" required/><textarea name="description" placeholder="说明"/><select name="assetType"><option value="PDF">PDF</option><option value="IMAGE">图片</option><option value="EXTERNAL_LINK">外链</option></select><select name="openMode"><option value="SAME_TAB">当前页面</option><option value="NEW_TAB">新页面</option></select><input name="storageKey" placeholder="对象存储键（PDF/图片）"/><input name="externalUrl" type="url" placeholder="外链地址"/><input name="sortOrder" type="number" min="0" defaultValue="0"/><select name="status" defaultValue="DRAFT">{statusOptions}</select><button>创建资料</button></form><h2>资料列表</h2>{assets.map(asset=><section key={asset.id} className="admin-card"><form action={updateAssetAction} className="admin-form"><input type="hidden" name="id" value={asset.id}/><input type="hidden" name="reportCardId" value={id}/><input name="title" defaultValue={asset.title} required/><textarea name="description" defaultValue={asset.description ?? ""}/><select name="assetType" defaultValue={asset.assetType}><option value="PDF">PDF</option><option value="IMAGE">图片</option><option value="EXTERNAL_LINK">外链</option></select><select name="openMode" defaultValue={asset.openMode}><option value="SAME_TAB">当前页面</option><option value="NEW_TAB">新页面</option></select><input name="storageKey" defaultValue={asset.storageKey ?? ""}/><input name="externalUrl" type="url" defaultValue={asset.externalUrl ?? ""}/><input name="sortOrder" type="number" min="0" defaultValue={asset.sortOrder}/><select name="status" defaultValue={asset.contentStatus}>{statusOptions}</select><button>保存资料</button></form><form action={deleteAssetAction}><input type="hidden" name="id" value={asset.id}/><input type="hidden" name="reportCardId" value={id}/><button className="danger">软删除资料</button></form></section>)}</main>;
}
