import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("production deployment entrypoint", () => {
  it("blocks web startup until migrations, storage, public content, administrator seed and login verification succeed", () => {
    const entrypoint = readFileSync("deploy/start-production.sh", "utf8");
    const dockerfile = readFileSync("Dockerfile", "utf8");
    const compose = readFileSync("compose.production.yaml", "utf8");
    const pm2 = readFileSync("deploy/ecosystem.config.cjs", "utf8");
    const productionBuild = readFileSync("deploy/build-production.sh", "utf8");
    const packageJson = readFileSync("package.json", "utf8");
    const example = readFileSync(".env.example", "utf8");
    const contentSeed = readFileSync("scripts/seed-default-h5-content.ts", "utf8");
    const contentVerify = readFileSync("scripts/verify-default-h5-content.ts", "utf8");
    const nextConfig = readFileSync("next.config.ts", "utf8");
    const nginx = readFileSync("deploy/nginx/default.conf", "utf8");

    expect(entrypoint).toContain("set -eu");
    expect(entrypoint).toContain("pnpm prisma migrate deploy");
    expect(entrypoint).toContain("pnpm storage:ensure");
    expect(entrypoint).toContain("pnpm content:bootstrap");
    expect(entrypoint).toContain("pnpm content:verify");
    expect(entrypoint).toContain("pnpm admin:seed");
    expect(entrypoint).toContain("pnpm admin:verify");
    expect(entrypoint.indexOf("pnpm content:bootstrap")).toBeLessThan(entrypoint.indexOf("pnpm content:verify"));
    expect(entrypoint.indexOf("pnpm content:verify")).toBeLessThan(entrypoint.indexOf("pnpm admin:seed"));
    expect(entrypoint.indexOf("pnpm admin:verify")).toBeLessThan(entrypoint.indexOf("if [ -f server.js ]"));
    expect(entrypoint).toContain("exec node .next/standalone/server.js");
    expect(entrypoint).toContain("Run pnpm build:production before starting the service.");
    expect(dockerfile).toContain('CMD ["sh", "./deploy/start-production.sh"]');
    expect(dockerfile).toContain("RUN pnpm build:production");
    expect(dockerfile).toContain("COPY src/config ./src/config");
    expect(compose).toContain("condition: service_healthy");
    expect(example).toContain("ADMIN_SEED_USERNAME");
    expect(example).toContain("replace_with_admin_username");
    expect(contentSeed).toContain('process.argv.includes("--publish-shell")');
    expect(contentSeed).toContain('process.argv.includes("--repair-published-shell")');
    expect(contentSeed).toContain('contentStatus: "PUBLISHED"');
    expect(contentVerify).toContain("前台不可访问分类");
    expect(contentVerify).toContain("前台不可访问卡片");
    expect(pm2).toContain('script: "./deploy/start-production.sh"');
    expect(pm2).toContain('interpreter: "/bin/sh"');
    expect(packageJson).toContain('"start:production": "sh deploy/start-production.sh"');
    expect(packageJson).toContain('"build:production": "sh deploy/build-production.sh"');
    expect(packageJson).not.toContain("tsx --env-file=.env");
    expect(packageJson.match(/tsx --env-file-if-exists=\.env/g)).toHaveLength(8);
    expect(productionBuild).toContain("export NEXT_STANDALONE=true");
    expect(productionBuild).toContain("exec pnpm build");
    expect(nextConfig).toContain('source: "/design/:path*"');
    expect(nextConfig).toContain("public, max-age=86400, s-maxage=86400, stale-while-revalidate=86400");
    expect(nginx).toContain("location ^~ /_next/static/");
    expect(nginx).toContain("location ^~ /design/reports/test-report-");
    expect(nginx).toContain('add_header Cache-Control "public, max-age=31536000, immutable";');
    expect(nginx).toContain("gzip on;");
    expect(nginx).not.toMatch(/add_header Cache-Control [^;]+ always;/);
  });

  it("runs the required quality gates and mobile browser journeys in CI", () => {
    const workflow = readFileSync(".github/workflows/quality.yml", "utf8");
    const playwright = readFileSync("playwright.config.ts", "utf8");
    const packageJson = readFileSync("package.json", "utf8");
    expect(workflow).toContain("postgres:17-alpine");
    expect(workflow).toContain("minio/minio:RELEASE.2025-07-23T15-54-02Z");
    expect(workflow).toContain("pnpm install --frozen-lockfile");
    expect(workflow).toContain("pnpm lint");
    expect(workflow).toContain("pnpm typecheck");
    expect(workflow).toContain("pnpm test");
    expect(workflow).toContain("pnpm prisma:validate");
    expect(workflow).toContain("pnpm build");
    expect(workflow).toContain('E2E_FIXTURE_WRITES_ALLOWED: "true"');
    expect(workflow).toContain("POSTGRES_DB: honest_nutri_e2e");
    expect(workflow).toContain("S3_BUCKET: honest-nutri-reports-e2e");
    expect(workflow).toContain("playwright install --with-deps chromium webkit");
    expect(workflow).toContain("pnpm test:e2e");
    expect(workflow).toContain("ROLLBACK_REF: d984a8a");
    expect(workflow).toContain("git worktree add --detach");
    expect(workflow).toContain("pnpm test:e2e:rollback");
    expect(workflow).toContain("actions/upload-artifact@v4");
    expect(workflow).toContain("playwright-report");
    expect(workflow).toContain("test-results");
    expect(playwright).toContain('process.env.CI ? "pnpm start" : "pnpm dev"');
    expect(playwright).toContain('name: "android-chromium"');
    expect(playwright).toContain('name: "mobile-webkit-p1"');
    expect(playwright).not.toContain('devices["iPhone 13"]');
    expect(playwright).toContain("(?:p1-regression|report-image-viewer)\\.spec\\.ts");
    expect(packageJson).toContain('"test:e2e:p1"');
    expect(packageJson).toContain('"test:e2e:rollback"');
  });
});
